export * from './auth';
export * from './student';
export * from './schedule';
export * from './document';
export * from './g1nb';
export * from './g2nb';
export * from './g3nb';
export * from './g4nb';
export * from './gab';
export * from './gi';
export * from './loan'
